//
//  FLFacebookAPI.h
//  FBLogin
//
//  Created by Optimus Information on 18/10/12.
//  Copyright (c) 2012 Optimus Information. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <FacebookSDK/FacebookSDK.h>

typedef void (^FBApiCompletionHandler)(NSError *error, id data);

@interface FLFacebookAPI : NSObject

/** Get logged in user information.
 * Fetch profile information, profile image of the logged in user.
 */
-(void)getLoggedInUserInfo: (FBApiCompletionHandler)completionHandler;

/** Share status on facebook
 * This is to post message on wall which may contain link, check in, image, caption, text description
 * @param parameterDictionary: Dictionary containing data to be uploaded on the Facebook wall.
 * This method internally calls "requestCompleted" when status is uploaded on wall. 
 */
-(void) postMessageOnWall:(NSMutableDictionary *)parameterDictionary completionHandler:(FBApiCompletionHandler) completionHandler;

/** Upload photo on facebook
 * This is used to upload photo to facebbok. This will automatically create a new album on facebook with name of the application.
 * @param photoData: NSData representation of the photo. Convert the image captured via Camera or Gallery or Web image to NSData and pass as an argument to this method.  
  * This method internally calls "requestCompleted" when photo is uploaded/not uploaded on wall.
 */
-(void) uploadPhoto:(NSData *)photoData completionHandler:(FBApiCompletionHandler) completionHandler;

/** Return friend list associated to the login credentials.
 * fetch friend id, friend name, friend square size profile picture 
 * @param: Limit ot number of friends to be returned. 
 */
-(void)getFriendList:(int)countOfFriends completionHandler:(FBApiCompletionHandler)completionHandler;

/** Return friends posts associated to the login credentials.
 * fetch post id, message, description, comments related to the friends posts
 */
-(void)getFriendsPosts: (FBApiCompletionHandler)completionHandler;

/** Return posts associated to the login credentials.
 * fetch post id, message, description, comments related to the user posts
 * @param: Limit ot number of posts to be returned.
 */
-(void)getMyPosts:(int)countOfPosts completionHandler:(FBApiCompletionHandler)completionHandler;

/** Method to search friend from user friend list on the basis on name.
 * fetch username, first name, last name, id for the given name
 * @param Friend name to be searched.
 */
-(void)searchFriendByName:(NSString *)toBeSearchedFriendName completionHandler:(FBApiCompletionHandler)completionHandler;

/** Get authenticated token
 * fetch authenticated token generated by Facebook API
 */
-(void)getAuthenticationToken:(FBApiCompletionHandler)completionHandler;

/** Get expiry date of the token
 * fetch expiry date of authenticated token generated by Facebook API
 */
-(void)getExpiryDate:(FBApiCompletionHandler) completionHandler;

/** Set permissions once user session is live.
    * Sets 'publish_stream' permission so that user can publish data on the wall. 
 */
-(void)setActiveSessionPermission:(FBApiCompletionHandler)completionHandler;

/** Method to delete post/like.
 * fetch status whether post was deleted or not.
 * @param post id which is to be deleted.
 */
-(void)deletePost:(id) postIDString;

/** Method to like a post.
 * fetch status whether post was successfully liked or not.
 * @param post id which is to be liked.
 */
-(void)likePost:(id)postId;

/** Method to execute any valid FQL query
 * fetch values depending upon the parameters in the FQL
 * @param FQL query which is to be executed.
 */
-(void)getFQLResult:(NSString *)FQLQuery completionHandler:(FBApiCompletionHandler)completionHandler;


@end
